name = "Tachyon 1.19.2"
author = "JSH32"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b23528554029e9449274f701ef78b8f82f5eec9cb8fb6b574176bbd628d8eb10"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
