name = "Tachyon"
author = "JSH32"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "967118f901cebe1e0a36cf3716db68cc4359eaffd16efda04f4795f2213de615"

[versions]
fabric = "0.14.0"
minecraft = "1.18.2"
