name = "Tachyon"
author = "JSH32"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7ab3af5eff88250ada58dce4164ddf37587ea6dda97f793e40770832feaf70d"

[versions]
fabric = "0.14.0"
minecraft = "1.18.2"
