name = "Tachyon"
author = "JSH32"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c908fcce956ddcb3f7983bf417295c729610331efb75fcb710d0880bec5ac5"

[versions]
fabric = "0.14.0"
minecraft = "1.18.2"
