name = "Tachyon 1.19"
author = "JSH32"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5a412a9d715c6ae14352f1a4bdb78f5ec9d32eda5a7df34afdeeb53e582532c"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
