name = "Tachyon 1.19"
author = "JSH32"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccb396e66903fb20bb081d50f0485de8ef29cba40415bcc47b3c30ea9ec8176c"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
