name = "Tachyon 1.19"
author = "JSH32"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e103febdc2892d7408d5b8ae8de650c9e7f97723f9071078449ec37e88f6d6c"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
